apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
availabilityZones:
  - eu-central-1a
  - eu-central-1b
  - eu-central-1c
metadata:
  name: eks-fadi-1707-addons
  region: eu-central-1
  version: "1.29"
  tags:
    karpenter.sh/discovery: eks-fadi-1707-addons
    created-by: eks-workshop-v2
    env: eks-fadi-1707-addons
iam:
  withOIDC: true
vpc:
  cidr: 10.42.0.0/16
  clusterEndpoints:
    privateAccess: true
    publicAccess: true
addons:
  - name: vpc-cni
    version: 1.16.0
    configurationValues: '{"env":{"ENABLE_PREFIX_DELEGATION":"true", "ENABLE_POD_ENI":"true", "POD_SECURITY_GROUP_ENFORCING_MODE":"standard"},"enableNetworkPolicy": "true"}'
    resolveConflicts: overwrite
  - name: coredns
    version: latest # auto discovers the latest available
  - name: kube-proxy
    version: latest
  - name: aws-ebs-csi-driver
    wellKnownPolicies:      # add IAM and service account
      ebsCSIController: true
managedNodeGroups:
  - name: default
    desiredCapacity: 3
    minSize: 3
    maxSize: 6
    instanceType: t3.small
    privateNetworking: true
    releaseVersion: "1.29.0-20240129"
    updateConfig:
      maxUnavailablePercentage: 50
    labels:
      workshop-default: "yes"